<?php
/**
 * Logs tranaction failures within the store.
 * Mainly geared for reporting Sagepay errors.
 *
 * @author Dan Bower
 */
require_once($_SERVER['DOCUMENT_ROOT'] . '/log4php/Logger.php');

class OrderLoggingHooks
{

	/**
	 * @var $clientLogger a log4php Logger instance for the client.
	 */
	private $clientLogger;

	/**
	 * @var $bozbozLogger a log4php Logger instance for us.
	 */
	private $bozbozLogger;

	/**
	 * @var $sagepayCodes mapping of response codes to solutions.
	 */
	private $sagepayErrors = array(
		'NOTAUTHED' => 
			'The bank has declined this transaction, you will need to use another card and attempt the payment again. Unfortunately, we are not provided with the details as to why the transaction was declined and would advise that the shopper contacts their card issuer for more information.',

		'NOTAUTHED 200' => 
			'The Authorisation attempt has been declined by the bank for this transaction.  You will need to try a different card type.',

		'NOTAUTHED 2000' => 
			'Unfortunately, we are not provided with any details as to why the transaction has been declined by the bank and would advise that your customer contacts their card issuer for more information. This could be due to several reasons such as funds not being available, spending limit may have been reached or bank account has been closed.',

		'REJECTED 2001' => 
			'The transaction would have failed due to the fraud rulebase which you would have set up onto your account.  The only way to prevent this from happening, would be to remove or relax your current rulebase, however, this would apply to all your transactions.',

		'ERROR 2003' => 
			'You will receive this error message for usually one or two reasons - if your Terminal ID\'s have not been set up correctly with your merchant bank or if we are experiencing intermittent authorisation issues where we have not been able to contact your merchant bank when requesting authorisation. This will be due to the transaction timing out and will result in transactions not being authorised and being registered as failed payments.',

		'NOTAUTHED 2008' => 
			'Please check our system monitor page to ensure there are no current issues and that our servers are processing transactions as normal. The link is: http://www.sagepay.com/system_monitor.asp. If the monitor page is showing everything normal please contact Sage Pay directly.  You may wish to (or advise your shopper) to try the transaction again at a later time',

		'NOTAUTHED 2009' => 
			'Unfortunately, we are unable to authorise your transactions as the network connection to the bank is currently unavailable.',

		'ABORT 2013' => 
			'This is a notification  system message to inform you that the transaction was cancelled by the customer. There is no issue with the payment process as this would have be caused by the customer clicking on the Cancel button on the payment page.',
		
		'INVALID 3002' => 
			'This system message is generated when you have not supplied the correct value in the VPSTxId field.  It is likely that you received this message when you were attempting to perform an related action to an original transaction (such as a REPEAT, RELEASE, VOID, REFUND etc.) as the VPSTxId, which uniquely identifies a transaction to the Sage Pay system, is generated by us and returned back to you.',
		
		'INVALID 3003' => 
			'Currency fields should contain 3-letter ISO 4217 codes e.g. GBP for UK Sterling, USD for U.S Dollars. If you submit a value which is not in line with the SO 4217 codes and is not set up on your account, you will get this system message',
		
		'INVALID 3004' => 
			'You would be getting this system message if the amount fields contains any other chracters which is not numeric or are not correctly formatted to the correct number of decimal places for the specified currency.',

		'INVALID 3005' => 
			'The Sage Pay system has a maximum and minimum acceptable transaction value which equate to approximately 100,000GBP and 0.50GBP respectively, with approximate equivalents in other currencies. Unfortunately, we are unable to process transaction values outside of these ranges.  You will be receiving this system message if you are passing an amount that is outside of the supported range.',

		'INVALID 3006' => 
			'If you have sent an Amount field with an invalid number of digits after the decimal place. e.g. 123.456 instead of 123.46, then you will receive this system message. You may also get this if you send fractional values to currencies that do not have minor units (like Japanese Yen, JPY, which only accepts whole number amounts)',

		'INVALID 3015' => 
			'The BillingAddress field which you have provided is longer than what is required.  This field should contains up to 200 characters which is the maximum number allowed.',

		'INVALID 3016' => 
			'The BillingPostCode field which you have provided is longer than what is required.  This field should contain no more than 10 characters.',

		'INVALID 3018' => 
			'The GiftAid field specifies whether you wish to apply gift aid to the transaction.  If you do, then the payment page will display the relevant text to provide the shopper with the option to allow GiftAid to be applied.  If you have received this system message, then the value which you have provided in this field is not what is specified within the protocol.',

		'INVALID 3022' => 
			'The CustomerEMail field, if provided, can only contain up to a maximum of 255 characters.  It is likely that you are submitting several email addresses which is therefore generating this system message',

		'INVALID 3023' => 
			'The ContactFax field, if provided, can only contain a maximum of up to 20 characters.  If you are providing a value which has more that 20 characters then you will receive this system message.',

		'INVALID 3024' => 
			'Our system will send you this system message if the ContactNumber field  you are sending contains more than the maximum of 20 characters. ',
		
		'INVALID 3025' => 
			'The DeliveryPostCode field should not contain more than the maximum of 10 characters.  If you are sending more that 10 characters in this field, then you will receive this system message.',

		'INVALID 3026' => 
			'The DeliveryAddress field should not contain more than the maximum of 200 characters and anything more will generate this system message.',
		
		'INVALID 3027' => 
			'The BillingPostCode field can only contain a maximum of 10 characters and any values more than this will generate this system message.',

		'INVALID 3028' => 
			'You will receive this system message if the BillingAddress field contains more than 200 characters which is the maximum number allowed.',
			
		'INVALID 3032' => 
			'The Amount field value can only contain numbers with no separator characters and this should be formatted to the correct number of decimal places for the specified currency.  For example if your currency is GBP, the Amount field value can be sent as 123.45, 4567.89, 0.36, 12.30 but not as 123.456, 4,567.89, .36 or 12.3. ',

		'INVALID 3036' => 
			'Your original transaction registration should always contain a description field which should contain a brief description of the transaction being performed. This can be used to describe the goods being purchased or the nature of the transaction. This field should only contain alphanumeric characters and must be 100 characters or less.',

		'INVALID 3041' => 
			'The Basket field can contain a maximum of up to 7,500 characters and you will get this system message if you are sending more than 7,500 characters.',

		'INVALID 3042' => 
			'The CustomerName field can contain a maximum of 100 characters and you will need to check your code to ensure that you are not sending more than this.',

		'INVALID 4025' => 
			'You will need to ensure that the card issue number length is being passed as it is displayed exactly on the customer\'s card.  This will either be one or two digits long and if any additional characters or digits are entered you will be presented with this error message.',

		'REJECTED 4046' => 
			'The card scheme requires you to pass the 3D-Authentication process in order to proceed with your payment. If you receive this message, then you have failed to be authenticated through 3D-Secure and the card provider will not allow you to proceed with the transaction until you pass.',

		'INVALID 4048' => 
			'You will need to check to ensure that the card number length being provided is correct and that you are sending the full card number situated on the front of the card.  You must also ensure that there are no spaces within this card number.',

		'INVALID 5010' => 
			'You will need to ensure that you have provided a debit or credit card number within the card number box provided on the payment screens. The debit or credit card number entered must match that of the card type selected before you have been presented with the option of entering the debit or credit card details.',

		'INVALID 5011' => 
			'Your card number has failed our validity checks and appears to be incorrect.  Please check and re-enter.',

		'MALFORMED 5012' => 
			'You will need to ensure that you have entered the name of the credit or debit card holder within the edit box that has been provided on the payment page. If no value is entered here you will be presented with this error message.',

		'INVALID 5013' => 
			'The expiry date of the card that you have entered on the payment pages is in the past. You will need to check your card, and if it has expired, you will need to destroy the card and use a different card type for the transaction. ',

		'MALFORMED 5014' => 
			'The expiry date of the credit or debit card must be entered in the expiry date box provided on the payment screens in order to continue with the transaction.',

		'MALFORMED 5017' => 
			'You will need to enter the CV2 or card security code on the payment pages in order to continue.  If no security code (CV2/CVV) has been provided, you will receive this system message.',

		'INVALID 5019' => 
			'You have entered an incorrect value for the card security code which is invalid. Any values provided which is not numeric will generate this system message.',

		'MALFORMED 5020' => 
			'You must enter the address to which the card being used is registered in the card address box provided on the payment page.',

		'INVALID 5021' => 
			'You will not be able to enter more than 200 characters in the card address box on the payment pages.  If the address is longer than 200 characters, you will receive this system message.',

		'MALFORMED 5022' => 
			'You must enter the post code to which the card being used is registered in the post code box provided on the payment page in order to continue.',

		'INVALID 5023' => 
			'You will only be able to enter up to 10 characters in the card post code box on the payment pages.  If your post code is longer than 10 characters then please just enter the first 10 characters in order to continue.',

		'INVALID 5024 ' => 
			'You will only be able to enter up to 50 characters in the card holder name box on the payment pages.  Any value longer than this will generate this system message.',

		'INVALID 5026 ' => 
			'The CardNumber field provided does not contain a valid card number and may contain characters other than numbers such as letters. ',

		'INVALID 5027' => 
			'The CardStart date that has been entered is not a valid month and year combination.',

		'INVALID 5028' => 
			'The CardExpiry date that has been entered is not a valid month and year combination. ',

		'ERROR 5030' =>
			'This error message is presented for transactions processed through the Form integration method only and occurs when the Encryption Password being used does not match the password that we have registered in our system. This will not allow us to decode your transaction registration POST. '
	);

	/**
	 * Setup the OrderLoggingHooks object.
  	 */
	public function __construct() {		
		cms_listen_action('checkout_attempted_order', array($this, 'logAttemptedOrders'));			
		Logger::configure($_SERVER['DOCUMENT_ROOT'] . '/log4php/log4php.xml');		
		$this->clientLogger = Logger::getLogger('client');
		$this->bozbozLogger = Logger::getLogger('bozboz');
	}

	/**
	 * Called once an order has been attempted.
	 * @param Order $order The Order that was attempted.
	 */
	public function logAttemptedOrders($order) {		
		$sagepayCode = $this->getCode($order->errors['processing']);
		$sagepaySolution = $this->sagepayErrors[$sagepayCode];
		if(isset($sagepaySolution)) {			
			$this->clientLog($order, $sagepayCode);
			$this->bozbozLog($order);
		}
	}

	/**
	 * Log information for internal use. Removes sensitive data. 
	 * @param Order $order The Order that was attempted.
	 */
	private function bozbozLog($order) {
		$order->card_number = 0000000000;
		$order->card_expiryyear = 1970;
		$order->card_expirymonth = 1;
		$order->card_expiry = '1/1970';
		$order->issue_number = 000;
		$order->card_cvv = 000;
		$this->bozbozLogger->error(print_r($order, true));
	}

	/**
	 * Log information for use by the client's staff.
	 * @param Order $order The Order that was attempted.
	 */
	private function clientLog($order, $sagepayCode) {
		$message = "\n" . 'Customer details:' . "\n";
		$message .= 'Title: ' . $order->customer_title . "\n";
		$message .= 'First name: ' . $order->customer_firstname . "\n";
		$message .= 'Last name: ' . $order->customer_lastname . "\n";
		$message .= 'Phone number: ' . $order->customer_phone . "\n";
		$message .= 'Email: ' . $order->customer_email . "\n";
		$message .= 'Error code: ' . $sagepayCode . "\n";
		$message .= 'Problem: ' . $this->sagepayErrors[$sagepayCode] . "\n\n";
		$message .= 'You can get a full list of error codes along with solutions at http://www.sagepay.com/help/systemmessageindex';
		$this->clientLogger->error($message);
	}

	/**
	 * Parse out the error code from Sagepay's response.
	 * @param $sagepayResponse Sagepay's response.
	 * @return string Sagepay error code.
	 */
	private function getCode($sagepayResponse) {
		$sagepayCode = preg_split('@:@', $sagepayResponse);
		$sagepayCode = preg_split('@:@', $sagepayCode[1]);
		return trim($sagepayCode[0]);
	}

}

new OrderLoggingHooks();